# Generated by Django 5.1.7 on 2025-04-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': '零件主文件', 'verbose_name_plural': '零件主文件'},
        ),
    ]
